### PR TITLE
Time to pull of this plaster and merge

### PR DESCRIPTION
**Pull request by canwaf**
It's time to pull off this plaster, and merge gss_speedup with main, and start working on databaker features and improvements in their own branch to improve our ability to rollback changes when things break. This branch has turned into a form of main, and it's time to grasp the nettle and yank, etc etc.

This is step one of pushing our changes back further upstream after we at minimum document our changes.

I have asked for @ajtucker, @CharlesRendle, @mikeAdamss, @robons, and @rossbowen approval for this change so we can just get it done. I believe this is a suitable quorum, so I expect people to vote and don't let the decision fester.

If you five are happy with this first step to Making Things Marginally Better™, this is but the first step which doesn't impact any of our longer term choices but will make releasing changes to our databaker fork easier.

P.S. I will rename the HEAD branch to main afterwards.

### CODE REVIEW

**Comment by mikeAdamss** [comment]
databaker is pinned by commit id not branch, you can roll it back and forward whenever you want to. 

I'm not sure if object, but given we cant add release tags without clashing with sensible code databaker, what does this accomplish beyond giving us a databaker master thats not the databaker master?

**Comment by canwaf** [comment]
I believe it separates out our work so we can focus on individual feature branches. Right now everything goes in gss-speedup which acts as the main branch in its place.

**Comment by mikeAdamss** [comment]
To clarify, currently everything goes onto individual feature branches that are focussed on, which are then merged into gss_speedup when they've been completed and pr'd.

**Comment by mikeAdamss** [comment]
I guess my concern/point is that is if we have a pristine master branch (pristine as in the same as sensible code) if we want to push some changes that are less than everything upstream to them, we can merge the relevant commit from gss_speedup into our master, then pr our master into sensible codes (that's sort of what I had in mind, if I ever get around to it) which keeps them in sync.

whereas if we do this, to push any subset of changes upstream we'll have to branch our own master, hard reset to whatever commit we want to merge over, force push the truncated codebase to a branch, then pr that over to sensible code.

which while possible, is something I'd probably want a reason for doing.

**Comment by rossbowen** [comment]
Are we at a point yet where we have something we would want to push upstream to sensiblecode? Or if not, are we far away from that?

**Comment by mikeAdamss** [comment]
We've a few things we could and should tbh, the issue is the first and principle bit was a massive refactor of databaker internals (the performance bit). So it'd be great to push that upstream to start .. but... it's a complicated thing and would need significant explanation otherwise they'll have no idea what they're looking at.

So could do and would like to (and it'd be nice to document for our team as well) but it's not a small task, that's the main reason I haven't done it yet, hasn't seemed priority-ish enough (that and it seemed sensible we run on the code base for a bit before pushing it to the world).

**Pull request closed without merging**
